"""empty message

Revision ID: 4326b2486449
Revises: c4d4f590ec4c
Create Date: 2017-10-19 17:35:52.621000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4326b2486449'
down_revision = 'c4d4f590ec4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('boby_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'boby_html')
    # ### end Alembic commands ###
